// Autogenerated from Pigeon (v13.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by WTPigeon.
NSObject<FlutterMessageCodec> *WTPigeonGetCodec(void);

@protocol WTPigeon
- (void)sendTest:(NSString *)message error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpWTPigeon(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPigeon> *_Nullable api);

NS_ASSUME_NONNULL_END
