name: watchtower_sdk
description: Watchtower Flutter SDK
version: 0.4.5
# homepage:
publish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.1.0
  logger: ^1.3.0
  shared_preferences: ^2.5.2
  device_info_plus: ^11.3.2
  devicelocale: ^0.8.1
  encrypt: ^5.0.3
  package_info_plus: ^8.3.0
  # image: ^4.0.15
  fixnum: ^1.1.1
  crypto: ^3.0.6

  extended_shared_preferences:
    git:
      url: https://github.com/KrasnovVitaliy/extended_shared_preferences.git
      ref: main # branch name

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  cider: ^0.1.4

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
