name: watchtower_sdk
description: Watchtower Flutter SDK
version: 0.4.5
# homepage:
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.2.4
  logger: ^1.3.0
  shared_preferences: ^2.0.18
  device_info_plus: ^8.1.0
  devicelocale: ^0.6.0
  encrypt: ^5.0.1
  package_info_plus: ^4.0.2
  image: ^4.0.15
  fixnum: ^1.1.0
  crypto: ^3.0.2

  extended_shared_preferences:
    git:
      url: https://github.com/KrasnovVitaliy/extended_shared_preferences.git
      ref: main # branch name

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0
  cider: ^0.1.4

flutter:
